# Generated by Django 4.1.3 on 2023-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oneka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
    ]
